/** Community fee + rating window constants (INR / hours / days). */
const HOST_CREATE_FEE = 200;
const JOIN_FEE = 50;
const JOIN_CANCEL_REFUND = 25;
const RATING_GRACE_HOURS = 36;
const RATING_WINDOW_DAYS = 5;
const REPUTATION_DISPLAY_THRESHOLD = 10;
const DISCORD_OTP_TTL_MS = 5 * 60 * 1000;
const DISCORD_OTP_COOLDOWN_MS = 60 * 1000;

module.exports = {
  HOST_CREATE_FEE,
  JOIN_FEE,
  JOIN_CANCEL_REFUND,
  RATING_GRACE_HOURS,
  RATING_WINDOW_DAYS,
  REPUTATION_DISPLAY_THRESHOLD,
  DISCORD_OTP_TTL_MS,
  DISCORD_OTP_COOLDOWN_MS,
};
