/** Community fee + rating window constants (INR / hours / days). */
const HOST_CREATE_FEE = 50;
const JOIN_FEE = 10;
const RATING_GRACE_HOURS = 36;
const RATING_WINDOW_DAYS = 5;
const REPUTATION_DISPLAY_THRESHOLD = 10;
const MIN_EVENT_SPOTS = 1;
const MAX_EVENT_SPOTS = 100;

module.exports = {
  HOST_CREATE_FEE,
  JOIN_FEE,
  RATING_GRACE_HOURS,
  RATING_WINDOW_DAYS,
  REPUTATION_DISPLAY_THRESHOLD,
  MIN_EVENT_SPOTS,
  MAX_EVENT_SPOTS,
};
