-- Seed Indian cities from india_cities.json (skip existing name+state pairs)

UPDATE cities
SET name = 'Gurugram'
WHERE name = 'Gurgaon' AND state = 'Haryana';

UPDATE profiles SET city = 'Gurugram' WHERE city = 'Gurgaon';
UPDATE events SET city = 'Gurugram' WHERE city = 'Gurgaon';

INSERT INTO cities (name, state) VALUES
  ('Port Blair', 'Andaman and Nicobar Islands'),
  ('Anantapur', 'Andhra Pradesh'),
  ('Chittoor', 'Andhra Pradesh'),
  ('Eluru', 'Andhra Pradesh'),
  ('Guntur', 'Andhra Pradesh'),
  ('Kadapa', 'Andhra Pradesh'),
  ('Kakinada', 'Andhra Pradesh'),
  ('Kurnool', 'Andhra Pradesh'),
  ('Machilipatnam', 'Andhra Pradesh'),
  ('Nellore', 'Andhra Pradesh'),
  ('Ongole', 'Andhra Pradesh'),
  ('Rajahmundry', 'Andhra Pradesh'),
  ('Srikakulam', 'Andhra Pradesh'),
  ('Tirupati', 'Andhra Pradesh'),
  ('Vijayawada', 'Andhra Pradesh'),
  ('Visakhapatnam', 'Andhra Pradesh'),
  ('Along', 'Arunachal Pradesh'),
  ('Bomdila', 'Arunachal Pradesh'),
  ('Itanagar', 'Arunachal Pradesh'),
  ('Naharlagun', 'Arunachal Pradesh'),
  ('Pasighat', 'Arunachal Pradesh'),
  ('Tawang', 'Arunachal Pradesh'),
  ('Ziro', 'Arunachal Pradesh'),
  ('Bongaigaon', 'Assam'),
  ('Dibrugarh', 'Assam'),
  ('Guwahati', 'Assam'),
  ('Jorhat', 'Assam'),
  ('Karimganj', 'Assam'),
  ('Nagaon', 'Assam'),
  ('Silchar', 'Assam'),
  ('Sivasagar', 'Assam'),
  ('Tezpur', 'Assam'),
  ('Tinsukia', 'Assam'),
  ('Arrah', 'Bihar'),
  ('Begusarai', 'Bihar'),
  ('Bhagalpur', 'Bihar'),
  ('Bihar Sharif', 'Bihar'),
  ('Chhapra', 'Bihar'),
  ('Darbhanga', 'Bihar'),
  ('Gaya', 'Bihar'),
  ('Katihar', 'Bihar'),
  ('Munger', 'Bihar'),
  ('Muzaffarpur', 'Bihar'),
  ('Patna', 'Bihar'),
  ('Purnia', 'Bihar'),
  ('Saharsa', 'Bihar'),
  ('Chandigarh', 'Chandigarh'),
  ('Ambikapur', 'Chhattisgarh'),
  ('Bhilai', 'Chhattisgarh'),
  ('Bilaspur', 'Chhattisgarh'),
  ('Durg', 'Chhattisgarh'),
  ('Jagdalpur', 'Chhattisgarh'),
  ('Korba', 'Chhattisgarh'),
  ('Raigarh', 'Chhattisgarh'),
  ('Raipur', 'Chhattisgarh'),
  ('Rajnandgaon', 'Chhattisgarh'),
  ('Daman', 'Dadra and Nagar Haveli and Daman and Diu'),
  ('Diu', 'Dadra and Nagar Haveli and Daman and Diu'),
  ('Silvassa', 'Dadra and Nagar Haveli and Daman and Diu'),
  ('Delhi', 'Delhi'),
  ('New Delhi', 'Delhi'),
  ('Mapusa', 'Goa'),
  ('Margao', 'Goa'),
  ('Panaji', 'Goa'),
  ('Ponda', 'Goa'),
  ('Vasco da Gama', 'Goa'),
  ('Ahmedabad', 'Gujarat'),
  ('Anand', 'Gujarat'),
  ('Bharuch', 'Gujarat'),
  ('Bhavnagar', 'Gujarat'),
  ('Gandhinagar', 'Gujarat'),
  ('Jamnagar', 'Gujarat'),
  ('Junagadh', 'Gujarat'),
  ('Mehsana', 'Gujarat'),
  ('Morbi', 'Gujarat'),
  ('Nadiad', 'Gujarat'),
  ('Navsari', 'Gujarat'),
  ('Rajkot', 'Gujarat'),
  ('Surat', 'Gujarat'),
  ('Vadodara', 'Gujarat'),
  ('Vapi', 'Gujarat'),
  ('Ambala', 'Haryana'),
  ('Bhiwani', 'Haryana'),
  ('Faridabad', 'Haryana'),
  ('Gurugram', 'Haryana'),
  ('Hisar', 'Haryana'),
  ('Karnal', 'Haryana'),
  ('Kurukshetra', 'Haryana'),
  ('Panchkula', 'Haryana'),
  ('Panipat', 'Haryana'),
  ('Rohtak', 'Haryana'),
  ('Sirsa', 'Haryana'),
  ('Sonipat', 'Haryana'),
  ('Yamunanagar', 'Haryana'),
  ('Bilaspur', 'Himachal Pradesh'),
  ('Dharamshala', 'Himachal Pradesh'),
  ('Hamirpur', 'Himachal Pradesh'),
  ('Kullu', 'Himachal Pradesh'),
  ('Manali', 'Himachal Pradesh'),
  ('Mandi', 'Himachal Pradesh'),
  ('Shimla', 'Himachal Pradesh'),
  ('Solan', 'Himachal Pradesh'),
  ('Una', 'Himachal Pradesh'),
  ('Anantnag', 'Jammu and Kashmir'),
  ('Baramulla', 'Jammu and Kashmir'),
  ('Jammu', 'Jammu and Kashmir'),
  ('Sopore', 'Jammu and Kashmir'),
  ('Srinagar', 'Jammu and Kashmir'),
  ('Bokaro Steel City', 'Jharkhand'),
  ('Deoghar', 'Jharkhand'),
  ('Dhanbad', 'Jharkhand'),
  ('Giridih', 'Jharkhand'),
  ('Hazaribagh', 'Jharkhand'),
  ('Jamshedpur', 'Jharkhand'),
  ('Ramgarh', 'Jharkhand'),
  ('Ranchi', 'Jharkhand'),
  ('Ballari', 'Karnataka'),
  ('Belagavi', 'Karnataka'),
  ('Bengaluru', 'Karnataka'),
  ('Bidar', 'Karnataka'),
  ('Davanagere', 'Karnataka'),
  ('Hassan', 'Karnataka'),
  ('Hubballi-Dharwad', 'Karnataka'),
  ('Kalaburagi', 'Karnataka'),
  ('Mangaluru', 'Karnataka'),
  ('Mysuru', 'Karnataka'),
  ('Shivamogga', 'Karnataka'),
  ('Tumakuru', 'Karnataka'),
  ('Udupi', 'Karnataka'),
  ('Vijayapura', 'Karnataka'),
  ('Alappuzha', 'Kerala'),
  ('Kannur', 'Kerala'),
  ('Kasaragod', 'Kerala'),
  ('Kochi', 'Kerala'),
  ('Kollam', 'Kerala'),
  ('Kottayam', 'Kerala'),
  ('Kozhikode', 'Kerala'),
  ('Malappuram', 'Kerala'),
  ('Palakkad', 'Kerala'),
  ('Thiruvananthapuram', 'Kerala'),
  ('Thrissur', 'Kerala'),
  ('Kargil', 'Ladakh'),
  ('Leh', 'Ladakh'),
  ('Kavaratti', 'Lakshadweep'),
  ('Bhopal', 'Madhya Pradesh'),
  ('Chhindwara', 'Madhya Pradesh'),
  ('Dewas', 'Madhya Pradesh'),
  ('Gwalior', 'Madhya Pradesh'),
  ('Indore', 'Madhya Pradesh'),
  ('Jabalpur', 'Madhya Pradesh'),
  ('Katni', 'Madhya Pradesh'),
  ('Ratlam', 'Madhya Pradesh'),
  ('Rewa', 'Madhya Pradesh'),
  ('Sagar', 'Madhya Pradesh'),
  ('Satna', 'Madhya Pradesh'),
  ('Singrauli', 'Madhya Pradesh'),
  ('Ujjain', 'Madhya Pradesh'),
  ('Ahmednagar', 'Maharashtra'),
  ('Akola', 'Maharashtra'),
  ('Amravati', 'Maharashtra'),
  ('Aurangabad', 'Maharashtra'),
  ('Chandrapur', 'Maharashtra'),
  ('Dhule', 'Maharashtra'),
  ('Jalgaon', 'Maharashtra'),
  ('Kolhapur', 'Maharashtra'),
  ('Latur', 'Maharashtra'),
  ('Mumbai', 'Maharashtra'),
  ('Nagpur', 'Maharashtra'),
  ('Nanded', 'Maharashtra'),
  ('Nashik', 'Maharashtra'),
  ('Navi Mumbai', 'Maharashtra'),
  ('Pune', 'Maharashtra'),
  ('Sangli', 'Maharashtra'),
  ('Solapur', 'Maharashtra'),
  ('Thane', 'Maharashtra'),
  ('Bishnupur', 'Manipur'),
  ('Churachandpur', 'Manipur'),
  ('Imphal', 'Manipur'),
  ('Thoubal', 'Manipur'),
  ('Jowai', 'Meghalaya'),
  ('Nongstoin', 'Meghalaya'),
  ('Shillong', 'Meghalaya'),
  ('Tura', 'Meghalaya'),
  ('Aizawl', 'Mizoram'),
  ('Champhai', 'Mizoram'),
  ('Lunglei', 'Mizoram'),
  ('Serchhip', 'Mizoram'),
  ('Dimapur', 'Nagaland'),
  ('Kohima', 'Nagaland'),
  ('Mokokchung', 'Nagaland'),
  ('Tuensang', 'Nagaland'),
  ('Balasore', 'Odisha'),
  ('Baripada', 'Odisha'),
  ('Berhampur', 'Odisha'),
  ('Bhadrak', 'Odisha'),
  ('Bhubaneswar', 'Odisha'),
  ('Cuttack', 'Odisha'),
  ('Puri', 'Odisha'),
  ('Rourkela', 'Odisha'),
  ('Sambalpur', 'Odisha'),
  ('Karaikal', 'Puducherry'),
  ('Mahe', 'Puducherry'),
  ('Puducherry', 'Puducherry'),
  ('Yanam', 'Puducherry'),
  ('Amritsar', 'Punjab'),
  ('Bathinda', 'Punjab'),
  ('Firozpur', 'Punjab'),
  ('Hoshiarpur', 'Punjab'),
  ('Jalandhar', 'Punjab'),
  ('Ludhiana', 'Punjab'),
  ('Moga', 'Punjab'),
  ('Mohali', 'Punjab'),
  ('Pathankot', 'Punjab'),
  ('Patiala', 'Punjab'),
  ('Ajmer', 'Rajasthan'),
  ('Alwar', 'Rajasthan'),
  ('Bharatpur', 'Rajasthan'),
  ('Bhilwara', 'Rajasthan'),
  ('Bikaner', 'Rajasthan'),
  ('Chittorgarh', 'Rajasthan'),
  ('Jaipur', 'Rajasthan'),
  ('Jodhpur', 'Rajasthan'),
  ('Kota', 'Rajasthan'),
  ('Nathdwara', 'Rajasthan'),
  ('Pali', 'Rajasthan'),
  ('Rajsamand', 'Rajasthan'),
  ('Sikar', 'Rajasthan'),
  ('Sri Ganganagar', 'Rajasthan'),
  ('Udaipur', 'Rajasthan'),
  ('Gangtok', 'Sikkim'),
  ('Gyalshing', 'Sikkim'),
  ('Mangan', 'Sikkim'),
  ('Namchi', 'Sikkim'),
  ('Chennai', 'Tamil Nadu'),
  ('Coimbatore', 'Tamil Nadu'),
  ('Dindigul', 'Tamil Nadu'),
  ('Erode', 'Tamil Nadu'),
  ('Kanchipuram', 'Tamil Nadu'),
  ('Madurai', 'Tamil Nadu'),
  ('Salem', 'Tamil Nadu'),
  ('Thanjavur', 'Tamil Nadu'),
  ('Thoothukudi', 'Tamil Nadu'),
  ('Tiruchirappalli', 'Tamil Nadu'),
  ('Tirunelveli', 'Tamil Nadu'),
  ('Tiruppur', 'Tamil Nadu'),
  ('Vellore', 'Tamil Nadu'),
  ('Hyderabad', 'Telangana'),
  ('Karimnagar', 'Telangana'),
  ('Khammam', 'Telangana'),
  ('Mahbubnagar', 'Telangana'),
  ('Nalgonda', 'Telangana'),
  ('Nizamabad', 'Telangana'),
  ('Ramagundam', 'Telangana'),
  ('Warangal', 'Telangana'),
  ('Agartala', 'Tripura'),
  ('Dharmanagar', 'Tripura'),
  ('Kailashahar', 'Tripura'),
  ('Udaipur', 'Tripura'),
  ('Agra', 'Uttar Pradesh'),
  ('Aligarh', 'Uttar Pradesh'),
  ('Bareilly', 'Uttar Pradesh'),
  ('Faizabad', 'Uttar Pradesh'),
  ('Firozabad', 'Uttar Pradesh'),
  ('Ghaziabad', 'Uttar Pradesh'),
  ('Gorakhpur', 'Uttar Pradesh'),
  ('Jhansi', 'Uttar Pradesh'),
  ('Kanpur', 'Uttar Pradesh'),
  ('Lucknow', 'Uttar Pradesh'),
  ('Mathura', 'Uttar Pradesh'),
  ('Meerut', 'Uttar Pradesh'),
  ('Moradabad', 'Uttar Pradesh'),
  ('Muzaffarnagar', 'Uttar Pradesh'),
  ('Noida', 'Uttar Pradesh'),
  ('Prayagraj', 'Uttar Pradesh'),
  ('Rampur', 'Uttar Pradesh'),
  ('Saharanpur', 'Uttar Pradesh'),
  ('Shahjahanpur', 'Uttar Pradesh'),
  ('Varanasi', 'Uttar Pradesh'),
  ('Dehradun', 'Uttarakhand'),
  ('Haldwani', 'Uttarakhand'),
  ('Haridwar', 'Uttarakhand'),
  ('Kashipur', 'Uttarakhand'),
  ('Nainital', 'Uttarakhand'),
  ('Rishikesh', 'Uttarakhand'),
  ('Roorkee', 'Uttarakhand'),
  ('Rudrapur', 'Uttarakhand'),
  ('Asansol', 'West Bengal'),
  ('Baharampur', 'West Bengal'),
  ('Bardhaman', 'West Bengal'),
  ('Darjeeling', 'West Bengal'),
  ('Durgapur', 'West Bengal'),
  ('Habra', 'West Bengal'),
  ('Kharagpur', 'West Bengal'),
  ('Kolkata', 'West Bengal'),
  ('Malda', 'West Bengal'),
  ('Siliguri', 'West Bengal')
ON CONFLICT (name, state) DO NOTHING;
